apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: test-component-fcsm
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-component-fcsm
    app.kubernetes.io/part-of: test-app-coyu
  name: test-component-fcsm
  namespace: build-e2e-hacbs-ugmi
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: test-component-fcsm
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: test-component-fcsm
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/test-images:630abc7c85044bf8aaf5662d7386c8a7
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 8081
          initialDelaySeconds: 10
          periodSeconds: 10
        name: container-image
        ports:
        - containerPort: 8081
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 10
          tcpSocket:
            port: 8081
        resources: {}
status: {}
